
const a1data = [
    {
        "id": 1,
        "title": "The Alphabet",
        "image": '',
        "vocab": [ 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 
        'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z',
        'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm',
        'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z' ],
        "vocabimages": [],
    },
    {
        "id": 2,
        "title": "Hello and Goodbye",
        "image": '',
        "vocab": [ 'hi', 'hello', 'goodbye', 'name', "What's your name?", "My name is _____.", "How are you?",
        "I'm fine.", "How old are you?", "I am ___ years old.", "Where do you live?", "I live in _____.",
        'bye', 'goodbye', "See you later!", "Have a good day!", "Good morning!", "Good afternoon!", "Good evening!", "Good night!", 
        'fine', 'happy', 'sad', 'angry', 'tired', 'America', 'China', 'Mexico', 'Canada' ],
        "vocabimages": [],
    },   
    {
        "id": 3,
        "title": "Numbers",
        "image": '',
        "vocab": [ 'zero', 'one', 'two', 'three', 'four', 'five', 'six', 'seven', 'eight', 'nine', 'ten',
        'eleven', 'twelve', 'thirteen', 'fourteen', 'fifteen', 'sixteen', 'seventeen', 'eighteen', 'nineteen',
        'twenty', 'thirty', 'forty', 'fifty', 'sixty', 'seventy', 'eighty', 'ninety', 'one hundred',
        'one thousand', 'one million', 'numbers', 'counting'  ],
        "vocabimages": [],
    },   
    {
        "id": 4,
        "title": "Colors",
        "image": '',
        "vocab": [ 'black', 'white', 'blue', 'red', 'yellow', 'green', 'orange', 'pink', 'purple', 'gray', 'brown',
        'light', 'dark', 'gold', 'silver', 'rainbow' ],
        "vocabimages": [],
    },   
    {
        "id": 5,
        "title": "Doing Things",
        "image": '',
        "vocab": [ 'ask', 'answer', 'bring', 'buy', 'call', 'choose', 'close', 'come', 'do', 'explain',
        'get', 'give', 'have', 'help', 'know', 'learn', 'like', 'listen', 'live', 'love', 'meet', 
        'open', 'play', 'read', 'say', 'see', 'sit', 'sleep', 'spell', 'start', 'stop', 'teach', 'want', 'wake', 'work', 'write' ],
        "vocabimages": [],
    },   
    {
        "id": 6,
        "title": "Family",
        "image": '',
        "vocab": [ 'mom', 'dad', 'mother', 'father', 'girl', 'boy', 'man', 'woman', 'baby', 'grandpa', 'grandma', 'parents', 'grandparents', 
        'sister', 'brother', 'son', 'daughter', 'children', 'wife','aunt', 'uncle', 'cousin', 'family', 'friend', 'people', 'home'],
        "vocabimages": [],
    },   
    {
        "id": 7,
        "title": "Daily Life",
        "image": '',
        "vocab": [ 'morning', 'afternoon', 'evening', 'night', 'day', 'yesterday', 'tomorrow', 'week', 'weekend',
        'beginning', 'end', 'house', 'city',  ],
        "vocabimages": [],
    },   
    {
        "id": 8,
        "title": "Food and Drink",
        "image": '',
        "vocab": [ 'food', 'drinks', 'meal', 'breakfast', 'lunch', 'dinner', 'dessert', 'fruit', 'vegetable', 'apple', 'banana', 'orange', 'strawberry',
        'tomato', 'potato', 'onion', 'carrot', 'salad', 'rice', 'noodles', 'bread', 'soup', 'meat', 'chocolate', 'chips', 
        'pizza', 'hamburger', 'cake', 'ice cream', 'milk', 'coffee', 'tea', 'juice', 'soda', 'water',
        'plate', 'bowl', 'spoon', 'fork', 'knife', 'cook', 'eat', 'drink', 'hungry', 'thirsty'  ],
        "vocabimages": [],
    },   
    {
        "id": 9,
        "title": "Weather and Seasons",
        "image": '',
        "vocab":  [ 'weather', 'sunny', 'rainy', 'snowy', 'windy', 'cloudy', 'hot', 'cold', 
        'seasons', 'spring', 'summer', 'winter', 'fall' ],
        "vocabimages": [],
    },   
    {
        "id": 10,
        "title": "Time and Dates",
        "image": '',
        "vocab": [ 'time', 'date', 'week', 'month', 'year', 'calendar', 'clock', "__ o'clock", 'hour', 'minute', 
        'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday', 
        'January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September',
        'October', 'November', 'December' ],
        "vocabimages": [],
    },   
    {
        "id": 11,
        "title": "Body and Clothing",
        "image": '',
        "vocab": [ 'body', 'head', 'hands', 'feet', 'arms', 'legs', 'stomach', 'hair', 'eyes', 'mouth', 'nose',
        'fingers', 'toes', 'clothing', 'wear', 'dress', 'shirt', 'sweater', 'pants', 'skirt', 'shoes', 'socks', 
        'underwear', 'gloves', 'hat', 'coat', 'jacket', 'scarf', 'umbrella', 'purse', 'wallet' ],
        "vocabimages": [],
    },   
    {
        "id": 12,
        "title": "Going Places",
        "image": '',
        "vocab": [ 'north', 'south', 'east', 'west', 'place', 'city', 'country', 'world', 'map', 'travel', 'car', 'bike', 
                    'boat', 'bus', 'taxi', 'plane', 'passport', 'building', 'park', 'house', 'school', 'office', 'restaurant', 
                    'theater', 'police', 'hospital', 'store', 'tourist', 'traffic', 'city', 'road', 'street', 
                    'language', 'visit', 'vacation'  ],
        "vocabimages": [],
    },   
]



const a1_nouns = ['action', 'actor', 'actress', 'advice', 'afternoon', 'air', 'airport', 'animal', 'answer', 'apple', 'April',
            'area', 'arm', 'art', 'article', 'artist', 'August', 'aunt', 'baby', 'bag', 'ball', 'banana', 'band', 'bank', 'baseball', 'basketball',
            'bath', 'bathroom', 'beach', 'bed', 'bedroom', 'beginning', 'bicycle', 'bike', 'bird', 'birthday', 'black', 'blog', 'blue', 'boat',
            'body', 'boot', 'bottle', 'box', 'boy', 'boyfriend', 'bread', 'break', 'breakfast', 'brother', 'brown', 'building', 'bus', 'business',
            'butter', 'cafe', 'cake', 'call', 'camera', 'capital', 'car', 'card', 'career', 'carrot', 'cat', 'CD', 'cent', 'change', 'cheese',
            'chicken', 'child', 'chocolate', 'city', 'class', 'clock', 'clothes', 'club', 'coat', 'coffee', 'cold', 'college', 'color', 'company',
            'concert', 'conversation', 'cooking', 'cost', 'cotton', 'country', 'course', 'cousin', 'cow', 'culture', 'cup', 'customer', 'dad',
            'dance', 'dancer', 'dancing', 'daughter', 'day', 'December', 'description', 'design', 'desk', 'dialogue', 'dictionary', 'diet',
            'difference', 'dinner', 'dish', 'doctor', 'dog', 'dollar', 'door', 'dress', 'drink', 'driver', 'DVD', 'ear', 'east', 'egg', 'elephant',
            'email', 'end', 'euro', 'evening', 'event', 'exam', 'example', 'exercise', 'eye', 'fact', 'fall', 'family', 'farmer', 'father',
            'favorite', 'February', 'feeling', 'festival', 'flight', 'floor', 'flower', 'food', 'foot', 'football', 'form', 'Friday', 'friend',
            'front', 'fruit', 'game', 'garden', 'geography', 'girl', 'girlfriend', 'glass', 'goodbye', 'grandfather', 'grandmother', 'grandparent',
            'gray', 'green', 'group', 'guess', 'guitar', 'gym', 'hair', 'hat', 'health', 'hello', 'help', 'history', 'hobby', 'homework', 'horse',
            'hospital', 'hotel', 'hour', 'house', 'husband', 'ice', 'ice', 'idea', 'information', 'interest', 'internet', 'interview', 'island',
            'jacket', 'January', 'jeans', 'job', 'juice', 'July', 'June', 'kind', 'kitchen', 'language', 'laugh', 'lecture', 'leg', 'lesson',
            'letter', 'library', 'life', 'lion', 'list', 'love', 'lunch', 'luxury', 'magazine', 'mall', 'man', 'March', 'May', 'meal', 'meaning',
            'meat', 'meeting', 'member', 'menu', 'message', 'meter', 'midnight', 'mile', 'milk', 'minute', 'mom', 'moment', 'Monday', 'money',
            'month', 'morning', 'mother', 'mountain', 'mouse', 'mouth', 'movie', 'museum', 'music', 'name', 'neighbor', 'neighborhood', 'news',
            'newspaper', 'night', 'north', 'nose', 'November', 'nurse', 'ocean', 'October', 'office', 'onion', 'opinion', 'opposite', 'orange',
            'order', 'page', 'paint', 'painting', 'pair', 'pants', 'paper', 'paragraph', 'parent', 'park', 'part', 'partner', 'party', 'passport',
            'pen', 'pencil', 'people', 'pepper', 'period', 'person', 'phone', 'photo', 'phrase', 'piano', 'piece', 'pig', 'pink', 'plan', 'plane',
            'play', 'player', 'police', 'policeman', 'pool', 'post', 'potato', 'pound', 'practice', 'problem', 'product', 'purple', 'quarter', 'radio',
            'rain', 'reader', 'reading', 'reason', 'red', 'restaurant', 'return', 'rice', 'right', 'river', 'road', 'room', 'salad', 'salt', 'sandwich',
            'Saturday', 'school', 'science', 'scientist', 'second', 'section', 'September', 'sheep', 'shirt', 'shoe', 'shop', 'shopping', 'show',
            'shower', 'singer', 'sister', 'situation', 'skill', 'skirt', 'snake', 'snow', 'son', 'song', 'soup', 'south', 'space', 'spelling',
            'sport', 'statement', 'station', 'stop', 'story', 'street', 'student', 'study', 'style', 'success', 'sugar', 'summer', 'sun', 'Sunday',
            'supermarket', 'sweater', 'swimming', 'table', 'taxi', 'tea', 'teacher', 'team', 'teenager', 'telephone', 'television', 'tennis', 'test',
            'thanks', 'theater', 'thing', 'Thursday', 'ticket', 'today', 'toilet', 'tomato', 'tomorrow', 'tonight', 'tooth', 'topic', 'tourist',
            'town', 'traffic', 'travel', 'truck', 'T-shirt', 'Tuesday', 'turn', 'TV', 'umbrella', 'uncle', 'university', 'vacation', 'vegetable',
            'video', 'visit', 'visitor', 'waiter', 'wake', 'wall', 'watch', 'weather', 'website', 'Wednesday', 'week', 'weekend', 'west', 'white',
            'wife', 'window', 'wine', 'winter', 'woman', 'word', 'work', 'worker', 'world', 'writer', 'writing', 'yard', 'year', 'yellow', 'yesterday']

const a1_verbs = ['add', 'agree', 'answer', 'arrive', 'ask', 'be', 'become', 'begin', 'believe', 'born', 'break', 'bring', 'build', 'buy', 'call', 'can',
            'cannot', 'carry', 'change', 'choose', 'clean', 'come', 'compare', 'complete', 'correct', 'cost', 'cotton', 'create', 'dance', 'decide',
            'describe', 'design', 'die', 'discuss', 'do', 'draw', 'dress', 'drink', 'eat', 'email', 'end', 'enjoy', 'exercise', 'explain', 'fall',
            'fill', 'find', 'follow', 'forget', 'form', 'get', 'give', 'grow', 'guess', 'happen', 'have', 'hear', 'help', 'house', 'imagine', 'improve',
            'include', 'interest', 'interview', 'introduce', 'join', 'keep', 'know', 'laugh', 'learn', 'let', 'lie', 'list', 'listen', 'live', 'lose',
            'love', 'mean', 'meet', 'miss', 'must', 'name', 'open', 'order', 'paint', 'park', 'phone', 'plan', 'play', 'post', 'practice',
            'prefer', 'prepare', 'put', 'rain', 'read', 'relax', 'remember', 'return', 'say', 'see', 'sell', 'send', 'shop', 'should', 'show',
            'sing', 'sit', 'snow', 'speak', 'spell', 'spend', 'stop', 'study', 'take', 'teach', 'telephone', 'tell', 'test', 'thank', 'think',
            'travel', 'turn', 'understand', 'visit', 'wake', 'want', 'watch', 'wear', 'work', 'would', 'write' ]

const a1_adjectives = ['afraid', 'amazing', 'angry', 'awesome', 'bad', 'beautiful', 'big', 'black', 'blond', 'blue', 'bored', 'boring', 'brown', 'busy',
                 'capital', 'clean', 'cold', 'common', 'complete', 'correct', 'dangerous', 'delicious', 'difficult', 'dirty', 'early', 'east',
                 'easy', 'excited', 'exciting', 'expensive', 'false', 'family', 'famous', 'fantastic', 'fast', 'favorite', 'few', 'fine', 'friendly',
                 'front', 'full', 'funny', 'gray', 'great', 'green', 'happy', 'hard', 'healthy', 'hot', 'hungry', 'important', 'interested',
                 'interesting', 'large', 'late', 'lecture', 'long', 'main', 'married', 'modern', 'natural', 'near', 'new', 'nice', 'north', 'OK',
                 'old', 'online', 'only', 'open', 'opposite', 'orange', 'other', 'perfect', 'personal', 'pink', 'poor', 'popular', 'pretty', 'purple',
                 'quick', 'quiet', 'ready', 'red', 'rich', 'right', 'sad', 'same', 'short', 'sick', 'similar', 'small', 'smart', 'sorry', 'south',
                 'special', 'strong', 'tall', 'terrible', 'thirsty', 'tired', 'true', 'unpleasant', 'useful', 'well', 'west', 'white', 'wonderful',
                 'yellow']

const a1_pronouns = ['another', 'anyone', 'anything', 'both', 'each', 'enough', 'everybody', 'everyone', 'everything', 'few', 'her', 'him', 'I', 'it',
               'a lot', 'many', 'me', 'more', 'most', 'much', 'no', 'nobody', 'nothing', 'one', 'other', 'same', 'she', 'some', 'somebody', 'someone',
               'something', 'them', 'they', 'us', 'we', 'what', 'when', 'which', 'who', 'you', 'yourself']

const a1_adverbs = ['about', 'above', 'across', 'again', 'ago', 'also', 'always', 'apart', 'around', 'away', 'behind', 'below', 'down', 'each', 'early',
              'east', 'else', 'enough', 'ever', 'fast', 'hard', 'here', 'how', 'however', 'in', 'just', 'late', 'lecture', 'long', 'lot', 'maybe',
              'more', 'most', 'much', 'near', 'never', 'north', 'not', "o’clock", 'off', 'often', 'OK', 'on', 'online', 'only', 'opposite', 'out',
              'over', 'pretty', 'probably', 'quickly', 'quite', 'really', 'right', 'same', 'so', 'sometimes', 'soon', 'south', 'then', 'there',
              'through', 'today', 'together', 'tomorrow', 'tonight', 'too', 'twice', 'under', 'up', 'usually', 'well', 'west', 'when', 'where',
              'why', 'yesterday']

const a1_prepositions = ['about', 'above', 'across', 'around', 'at', 'behind', 'below', 'down', 'during', 'for', 'from', 'in', 'into', 'like', 'near',
                   'next', 'of', 'off', 'on', 'opposite', 'out', 'over', 'through', 'to', 'under', 'up', 'with', 'without']


export default a1data ;
