
const a1grammardata = [
    {
        "id": 1,
        "title": "Pronouns",
        "image": '',
        "vocab": [ 'I', 'you', 'he', 'she', 'it', 'we', 'they', 'me', 'him', 'her', 'us', 'them' ],
        "vocabimages": [],
    },
    {
        "id": 2,
        "title": "Adjectives",
        "image": '',
        "vocab": ['afraid', 'amazing', 'angry', 'bad', 'beautiful', 'big', 'black', 'blue', 'boring', 'brown', 'busy',
                'cold', 'correct', 'dangerous', 'delicious', 'early', 'east','easy', 'excited', 'expensive', 'false', 'fast', 
                'favorite', 'few', 'friendly','funny', 'gray', 'good', 'great', 'green', 'happy', 'hard', 'healthy', 'hot', 'hungry', 'important',
                'interesting', 'large', 'late', 'long', 'main', 'near', 'new', 'nice', 'north', 'OK', 'old', 'online', 'only', 'open', 'opposite', 
                'orange', 'other', 'perfect', 'pink', 'poor', 'pretty', 'purple','quiet', 'ready', 'red', 'rich', 'sad', 'same', 'short', 'sick', 
                'small', 'smart', 'sorry', 'south', 'special', 'strong', 'tall', 'thirsty', 'tired', 'true', 'west', 'white', 'wonderful',
                'yellow'],
        "vocabimages": [],
    },
    {
        "id": 3,
        "title": "Possessives",
        "image": '',
        "vocab": [ 'my', 'your', 'his', 'her', 'its', 'our', 'their',  ],
        "vocabimages": [],
    },
    {
        "id": 4,
        "title": "Questions",
        "image": '',
        "vocab": [ 'who', 'where', 'when', 'why', 'how', 'which', 'what' ],
        "vocabimages": [],
    },
    {
        "id": 5,
        "title": "Present Simple Tense",
        "image": '',
        "vocab": ['add', 'agree', 'answer', 'arrive', 'ask', 'be', 'become', 'begin', 'believe', 'born', 'break', 'bring', 'build', 'buy', 'call', 'can',
                'cannot', 'carry', 'change', 'choose', 'clean', 'come', 'compare', 'complete', 'correct', 'cost', 'cotton', 'create', 'dance', 'decide',
                'describe', 'design', 'die', 'discuss', 'do', 'draw', 'dress', 'drink', 'eat', 'email', 'end', 'enjoy', 'exercise', 'explain', 'fall',
                'fill', 'find', 'follow', 'forget', 'form', 'get', 'give', 'grow', 'guess', 'happen', 'have', 'hear', 'help', 'house', 'imagine', 'improve',
                'include', 'interest', 'interview', 'introduce', 'join', 'keep', 'know', 'laugh', 'learn', 'let', 'lie', 'list', 'listen', 'live', 'lose',
                'love', 'mean', 'meet', 'miss', 'must', 'name', 'open', 'order', 'paint', 'park', 'phone', 'plan', 'play', 'post', 'practice',
                'prefer', 'prepare', 'put', 'rain', 'read', 'relax', 'remember', 'return', 'say', 'see', 'sell', 'send', 'shop', 'should', 'show',
                'sing', 'sit', 'snow', 'speak', 'spell', 'spend', 'stop', 'study', 'take', 'teach', 'telephone', 'tell', 'test', 'thank', 'think',
                'travel', 'turn', 'understand', 'visit', 'wake', 'want', 'watch', 'wear', 'work', 'would', 'write' ],
        "vocabimages": [],
    },
    {
        "id": 6,
        "title": "Past Simple Tense",
        "image": '',
        "vocab": [   'added', 'agreed', 'answered', 'arrived', 'asked', 'was/were',
        'became', 'began', 'believed', 'was/were born', 'broke', 'brought', 'built',
        'bought', 'called', 'could', 'could not', 'carried', 'changed', 'chose', 'cleaned',
        'came', 'compared', 'completed', 'corrected', 'cost', 'was/were cotton',
        'created', 'danced', 'decided', 'described', 'designed', 'died', 'discussed',
        'did', 'drew', 'dressed', 'drank', 'ate', 'emailed', 'ended', 'enjoyed',
        'exercised', 'explained', 'fell', 'filled', 'found', 'followed', 'forgot',
        'formed', 'got', 'gave', 'grew', 'guessed', 'happened', 'had', 'heard',
        'helped', 'housed', 'imagined', 'improved', 'included', 'interested', 'interviewed',
        'introduced', 'joined', 'kept', 'knew', 'laughed', 'learned', 'let', 'lay',
        'listed', 'listened', 'lived', 'lost', 'loved', 'meant', 'met', 'missed',
        'had to', 'named', 'opened', 'ordered', 'painted', 'parked', 'phoned', 'planned',
        'played', 'posted', 'practiced', 'preferred', 'prepared', 'put', 'rained', 'read',
        'relaxed', 'remembered', 'returned', 'said', 'saw', 'sold', 'sent', 'shopped',
        'should', 'showed', 'sang', 'sat', 'snowed', 'spoke', 'spelled', 'spent',
        'stopped', 'studied', 'took', 'taught', 'telephoned', 'told', 'tested', 'thanked',
        'thought', 'traveled', 'turned', 'understood', 'visited', 'woke', 'wanted', 'watched',
        'wore', 'worked', 'would', 'wrote' ],
        "vocabimages": [],
    },
    {
        "id": 7,
        "title": "Adverbs",
        "image": '',
        "vocab": [ 'always', 'sometimes', 'never', 'here', 'there', 'now', 'yesterday', 'today', 'tomorrow',
        'soon', 'late', 'early', 'slowly', 'maybe', 'really' ],
        "vocabimages": [],
    },
    {
        "id": 8,
        "title": "Prepositions",
        "image": '',
        "vocab": ['about', 'above', 'across', 'around', 'at', 'behind', 'below', 'down', 'during', 'for', 'from', 'in', 'into', 'like', 'near',
        'next', 'of', 'off', 'on', 'opposite', 'out', 'over', 'through', 'to', 'under', 'up', 'with', 'without'],
        "vocabimages": [],
    },
    {
        "id": 9,
        "title": "Comparative and Superlative",
        "image": '',
        "vocab": [   'Big - Bigger - Biggest', 'Small - Smaller - Smallest', 'Tall - Taller - Tallest',
        'Short - Shorter - Shortest', 'Fast - Faster - Fastest', 'Slow - Slower - Slowest',
        'High - Higher - Highest', 'Low - Lower - Lowest', 'Old - Older - Oldest',
        'Young - Younger - Youngest', 'Good - Better - Best', 'Bad - Worse - Worst', ],
        "vocabimages": [],
    },
]

export default a1grammardata ;
